apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes metal.kube.um.edu.ar in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
    # We need this hack, to be able get private IPs resolution from nip.io
    # from external DNS (local dns resolver doesn't allow extn sources to return private IP addrs)
    nip.io:53 {
        errors
        cache 30
        forward . 8.8.8.8
    }
  Corefile-backup: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes metal.kube.um.edu.ar in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
