# Use kustomize to merge into cluster-kustom.yaml:
# - cluster.yaml (upstream)
# - cluster-tunables.yaml (committed in-tree)
# - cluster-nodes.yaml (autogenerated)
prep_cluster() {
    local cluster_nodes=cluster-nodes.yaml
    echo "Creating custom '${cluster_nodes}' per-node setup ..."
    ${MY_DIR}/generate-nodes.sh ${NODES:?} > ${MY_DIR}/../configs/${cluster_nodes}
    cd ${MY_DIR}/../configs || exit 1
    echo "Creating kustom '${CLUSTER_DST}' merged setup ..."
    test -s ${cluster_nodes} || { echo "FATAL: ${cluster_nodes} in zero" ; exit 1 ;}
    kustomize build > ${CLUSTER_DST}
}
MY_DIR=$(dirname ${0})
CLUSTER_DST=cluster-kustom.yaml
NODES=${*:? missing args: NODES}
set -eu
prep_cluster
