#!/bin/bash
# Simple generate-nodes.sh fixture test against already saved 'out',
# ab-uses /proc mount to mimic nodes -> directories generation for mounted FSs

test_status() {
    [ ${1} -eq 0 ] && echo "PASS: ${FUNCNAME[1]}" || echo "FAIL: ${FUNCNAME[1]}"
    return ${1}
}

do_gen_out() {
    ../scripts/generate-nodes.sh ${NODES}
}

yaml_to_json() {
    python -c 'import yaml,json,sys;print(json.dumps(yaml.load(sys.stdin)))'
}

test_generate_diff() {
    local f_out=fixtures/generates-nodes.out
    echo "TEST: Verifying no diff against ${f_out} ..."
    diff -u ${f_out} <(do_gen_out)
    test_status $?; return $?
}

test_prep_cluster_yaml() {
    ../scripts/10-do-prep.sh ${MANIFESTS_DIR:?} ${TMPDIR} ${NODES}
    echo "TEST: Verifying generated cluster.yaml has proper structure (to return injected nodes)..."
    local parsed_nodes=$(sed '1,/^kind:.CephCluster/d' ${TMPDIR}/cluster.yaml | \
        yaml_to_json | \
        jq -r '[.spec.storage.nodes[].name]|join(" ")')
    [ "${parsed_nodes}" = "${NODES}" ]
    test_status $?; return $?
}

do_test() {
    set -e
    test_generate_diff
    test_prep_cluster_yaml
}

# Output generated by `./generate-nodes_test.sh gen-out`
# using below environment is already saved to fixtures/
# for tests comparison
export GN_FSTYPE='proc'
export GN_PREFIX=/proc
export GN_SSH_CMD='sh -c'
NODES="foo bar"
TMPDIR=$(mktemp -d /tmp/tmp.kros-r-tests.XXXXXX)
trap 'rc=$?; rm -rf ${TMPDIR:?}; exit $rc' 0

case "$1" in
    test) do_test;;
    gen-out) do_gen_out;;
esac
